### ISSUE TITLE
write the content for "i'm thinking about pitching an idea" section

### ISSUE THREAD

**Issue by carodew** [GSA/10x#40]
## it should …

- [ ] pull from existing 10x content (esp. what the writing lab has already reviewed)

## it should include (not in order) …
- [ ] Eligibility information (people and ideas) in encouraging language
- [ ] information about what a TTS sponsor is and how to get one
- [ ] short list of previous pitches that have been approved
- [ ] what makes a good pitch
- [ ] sample pitch
- [ ] show criteria for scoring
- [ ] how to ask for help in creating your pitch 
- [ ] examples of successful projects that have gone through the system (short list)

## it's done when …
- [ ] the team has agreed upon the content and there are no more comments/suggestions in the doc
- [ ] the content is ready to be used in wireframes/mock ups

**Comment by carodew** [comment]
@willcahoe this feels like a lot of work for one ticket, should we break this up into two tickets or just leave it as is? I'm just trying to think about how we can move this to `done` a little faster, although that may just be more confusing than leaving it as is. Open to your thoughts.

**Comment by willcahoe** [comment]
@carodew I'm fine leaving as is, not need for additional tickets

**Comment by willcahoe** [comment]
Updated the definition of done to include:

- [ ] the content is ready to be used in wireframes/mock ups

**Comment by willcahoe** [comment]
# I'm thinking about pitching an idea to 10x...

## Questions to answer

- [ ] Am I/is my idea eligible for 10x funding?
- [ ] What makes a good pitch?
- [ ] Can I see a short list of pitches that have received funding?
- [ ] Can I see a sample pitch? 
- [ ] What is the scoring criteria?
- [ ] Can someone help me craft a pitch?
- [ ] What are some projects that have gone through the 10x funding process? 
- [ ] What is a TTS Sponsor and how do I get one?

## Eligibility

Any federal employee from any agency is eligible to submit an idea for 10x funding. We are not able to accept pitches from Federal contractors at this time.

Your idea is eligible if it falls under the 10x funding authority (Digital Services Fund) which is designed to fund *new, good-for-government technology products or services that have the potential to create impact for multiple agencies or a large portion of the public*.

Furthermore, the 10x team is interested in funding projects that sit in a big or rapidly growing market within the government and support not just the government but also the contracting ecosystem. 

## Good Pitches

A good pitch answers a simple question in 2 or 3 sentences, “What problem are you trying to solve?”

Your pitch should:

* Demonstrate a clear understanding of the problem you want to solve
* Describe how it meets the DSF goal of funding new, good-for-government products or services
* Be as narrative as possible 

## Writing your Pitch

Don’t know where to begin? Need a second pair of eyes or a gut check with a technical expert? Send us an email at 10x@gsa.gov and someone from our team will help you craft the perfect pitch.

## Past pitches



**Pitch Title: Open Source Translation Services**
60.6 million Americans are not fluent in English. Despite this, most Federal web content is only available in English. Having content available in multiple languages will make the information we produce more accessible to the members of the public whose primary language is not English. This can be done with existing open source tools for delivering localized content such as Pootle and gettext. TTS will investigate whether translation services could be shared as a GSA-sponsored service or as a reusable playbook.

**Pitch Title: Qualitative Data Management**
Each month, approximately 9,000 surveys are submitted through USA.gov and Gobierno.USA.gov. About 2,000 of these include open-ended comments. With current resource limitations, it's challenging to take advantage of this qualitative data. TTS will explore implementing a semi-automated product and/or process, using topic extraction, word/phrase frequencies, or other applications of text analysis, to help quickly respond to user feedback.

**Pitch Title: PRA.Gov**
OMB’s Office of Information and Regulatory Affairs (OIRA) is charged with overseeing Federal compliance with the Paperwork Reduction Act (PRA). Agencies often cite frustration with accessing and understanding OMB’s policies on the PRA, which are spread across numerous inaccessible PDFs. This situation has reduced compliance and created delays in the approval of information collection requests (ICRs). Through outreach to PRA desk officers and agency staff, and in consultation with OIRA, TTS will explore what it would take to modernize the way agencies interact with OMB’s policies in order to design an accessible, user-friendly online interface to respond to agency inquiries.

## Scoring and Criteria

Your pitch will be rated based on the following 3 criteria, each given equal weight:
* *Clarity*. The proposal’s understanding and explanation of the problem that needs to be solved
* *Alignment*. The degree to which addressing this problem aligns with the 10x funding authority 
  * New, good-for-government technology products or services
* *Impact*. The potential impact of solving this problem on the federal government or the American public

## TTS Sponsorship 

### "What's a TTS Sponsor?"

10x sits in the Technology Transformation Services (TTS) at GSA, and TTS manages the Digital Services Fund. That means that all 10x projects, regardless of where they originated, are owned by TTS. Your TTS Sponsor will be someone who believes in your idea and will serve as the product manager to shepherd the project to success. Your role will be that of a subject matter expert and you can be involved in the process as much or as little as you are able. TTS has expertise in product ownership and will be the default home of any deliverables or outcomes of your project; however, our team will advocate for any project deliverables to live in the most logical place.

### "How do I get a TTS Sponsor?"

You do not need a sponsor to submit an idea to 10x. If your project is accepted for funding, we will connect you with a sponsor.

**Comment by willcahoe** [comment]
@carodew 
@thebestsophist 

This content draft is ready for reviewing

**Comment by shawnique** [comment]
Content in Research phase
