### ISSUE TITLE
Research what required statements we need to include in the footer

### ISSUE THREAD

**Issue by carodew** [GSA/10x#45]
## it should consider …
- [x] whether we need ones that are separate from the overall gsa.gov site 
- [x] Privacy, FOIA, Accessibility, any other required links, etc. 

## it's done when …
- [x] we've reached a yes/no conclusion on each one 
- [x] if yes, we've created issues to account for the work of creating them.

**Comment by willcahoe** [comment]
https://designsystem.digital.gov/components/footers/

**Comment by willcahoe** [comment]
https://www.digitalgov.gov/resources/required-web-content-and-links/

**Comment by willcahoe** [comment]
I've looked at guidance from USWDS and DigitalGov, I do not believe there are any specific regulations that govern what must or must not be included in Federal website footers. 

My approach is going to be "make the 10x.gsa.gov footer look like and provide similar content as the majority of other federal website footers, especially websites that TTS employees have designed or worked on"

My assumption is that, because TTS works on so many websites, we would know about the requirements already if there were any.

If you disagree with my assumption, please let me know. I was given the names of some contacts from OMB that I can reach out to, but I am not planning on doing so unless advised otherwise by the 10x website team.

@carodew @carodew @thisisdano
