### ISSUE TITLE
Gather current metrics

### ISSUE THREAD

**Issue by carodew** [GSA/10x#56]
In order to know if the website is actually benefiting the 10x program, we need some metrics. More specifically, we need to know what the current state is so we have something to compare against. 

## it should include …
- [x] Number of pitches for Phase 1 funding from previous rounds
- [x] Number of pitches for Phase 1 funding that list other agencies as SMEs (submitted through a TTS sponsor) 
- [x] Number of different agencies represented as SMEs on pitches for Phase 1 projects (for example, if pitch 1 has NIST as a SME and pitch 2 also has NIST as a SME, we'd only count NIST once. This is more about breadth than quantity). 
- [x] Count of inquiries from other agencies on how to set up a 10x-style program (if this is info we can gather, if not we may have to leave it out for now. It probably will take some creative email mining).
- [x] Count of consulting engagements with other agencies on running or setting up a 10x-style program

## it's done when …
- [x] We have a spreadsheet where these numbers are tracked that the entire team can access. 
- [x] (probably) those metrics are also public on the repo

## outstanding questions 
- do we only want to track Phase 1 or do we want to track later phases as well?

**Comment by carodew** [comment]
@willcahoe I'm happy to start working on this if you can point me to the right docs (if they exist)

**Comment by willcahoe** [comment]
@carodew I'm not sure if there is a nice place to gather this info from. I can get most of the information from the previous round (for the first three bullet points), but I don't know if we have good numbers from before I joined the project (great pitch)

**Comment by carodew** [comment]
Previous round is probably good enough.

**Comment by willcahoe** [comment]
In order to know if the website is actually benefiting the 10x program, we need some metrics. More specifically, we need to know what the current state is so we have something to compare against. 

## it should include …
- [ ] Number of pitches for Phase 1 funding from previous rounds: **85**
- [ ] Number of pitches for Phase 1 funding that list other agencies as SMEs (submitted through a TTS sponsor) **6**
- [ ] Number of different agencies represented as SMEs on pitches for Phase 1 projects (for example, if pitch 1 has NIST as a SME and pitch 2 also has NIST as a SME, we'd only count NIST once. This is more about breadth than quantity). **3**
- [ ] Count of inquiries from other agencies on how to set up a 10x-style program (if this is info we can gather, if not we may have to leave it out for now. It probably will take some creative email mining).
- [ ] Count of consulting engagements with other agencies on running or setting up a 10x-style program

## it's done when …
- [ ] We have a spreadsheet where these numbers are tracked that the entire team can access. 
- [ ] (probably) those metrics are also public on the repo

## outstanding questions 
- do we only want to track Phase 1 or do we want to track later phases as well?

**Comment by carodew** [comment]
@willcahoe what was the approximate time period of this round? I'm thinking of what we're going to call it when reported out – Fall 2017 round? or ... you know, the correct timeframe?

**Comment by willcahoe** [comment]
@carodew FY18 1st Quarter - although I don't want to assume that future rounds will fall nicely into Fiscal year quarters because....they probably won't

**Comment by carodew** [comment]
`¯\_(ツ)_/¯`
